name: Publish to PyPI

on:
  release:
    types: [published]  # Trigger khi tạo Release

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: pypi

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1